# key = { name, doing, desc, tags }

[forage]
	name="forage"
	doing="foraging"
	desc="Find and exploit natural resources in this area, such as plants or fungus."
	tags = [ "resource" ]

[mine]
	name="mine"
	doing="mining"
	desc="Find and exploit mineral resources in this area, such as rocks and metal ores."
	tags = [ "resource" ]

[search]
	name = "search"
	doing = "searching"
	desc = "Find secrets, hidden things, and lost items in this area."
	tags = [ "resource" ]
