# TOML encoding: prototype key is table name

# Equipment
[backpack]
	typeclass="typeclasses.storage_object.Backpack"
	prototype_desc = "A basic backpack."
	key="backpack"
	desc="A cloth satchel meant to be slung over your shoulder."
[belt]
	typeclass="typeclasses.storage_object.Belt"
	prototype_desc = "A belt, for carrying belt items."
	key="belt"
	desc="A leather strap that attaches to itself.  You can sling it around your waist and attach things to it."
[beltpouch]
	typeclass="typeclasses.storage_object.BeltStorage"
	prototype_desc = "A pouch for attaching to belts."
	key="pouch"
	desc="A small pouch with a hook for attaching to your belt.  If worn correctly, you can access its contents quickly."
[scabbard]
	typeclass="typeclasses.storage_object.BeltScabbard"
	prototype_desc="Basic scabbard, hangs on belt, holds swords."
	key="scabbard"
	desc = "A sword scabbard with a hook for attaching to your belt."
[shirt]
	typeclass="typeclasses.item.Shirt"
	prototype_desc="Basic shirt"
	key="shirt"
	desc = "A plain cloth shirt, needed to eat at fancy restaurants."
[pants]
	typeclass="typeclasses.item.Pants"
	prototype_desc="Basic pants"
	key="pants"
	desc="Plain cloth pants, miraculously in your size."

[trashcan]
	typeclass="typeclasses.storage_object.Destroyer"
	prototype_desc="Destroys any item placed inside, for debug use."
	key="trash can"
	scene_desc="There is a |wtrash can|n standing here."
	desc="Automagic trash disposal unit.  Place things inside to immediately destroy them."

# Resources
[berries]
	typeclass="typeclasses.resources.Resource"
	prototype_desc="test resource"
	key="$choice('blue','black','red','sour','green')berries"
	quality= { "randint"= [ 1, 10] }
[rotberries]
	prototype_parent="berries"
	key="$choice('rot','stink','crap','foul')berries"
	quality=0
[magicberries]
	prototype_parent="berries"
	key="magic $choice('blue','black','red','sour','green')berries"
	quality=10
[stick]
	typeclass="typeclasses.resources.Resource"
	prototype_desc="test resource"
	key="stick"
	quality= { "randint" = [ 1, 5 ] }
[stickystick]
	prototype_parent="stick"
	key="sticky stick"
	quality= { "randint" = [ 0, 1 ] }
[magicstick]
	prototype_parent="stick"
	key="magic stick"
	quality= { "randint" = [ 5, 10 ] }


[berrybush]
	typeclass="typeclasses.resources.ResourceNode"
	prototype_desc="Test resource node: sticks and berries @10/9-12."
	key = "berry bush"
	spawn_giver = true
	desc = "This low bush has many low branches containing a variety of berries."
	unseen_desc = "You notice a few bushes around."
	seen_desc = "You notice a |wberry bush|n among the scattered bushes."
	min_tier = 4
	max_tier = 6
	nominal_tier = 5
	rare_chance = 5
	trash_chance = 35
	[berrybush.resources]
		4 = { stick = 35, berries=15, "" = 50 }
		6 = { stick = 35, berries=50, "" = 15 }
		7 = { stick = 15, berries = 85 }
	[berrybush.rare]
		stick = "magicstick"
		berries = "magicberries"
	[berrybush.trash]
		stick = "stickystick"
		berries = "rotberries"
